version: "3.7"

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: MCEternal-1.3.4.zip
      MAX_MEMORY: 6G
    ports:
      - 25565:25565
    volumes:
      - minecraft-data:/data
    # deploy:
    #   resources:
    #     limits:
    #       memory: 10G
    healthcheck:
      start_period: 5m

volumes:
  minecraft-data:
